# Generated by Django 5.0.3 on 2024-04-29 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_answer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='item_answer',
            name='seller_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='app.seller'),
            preserve_default=False,
        ),
    ]
