# Generated by Django 5.0.3 on 2024-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_user_username_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='product_url',
            field=models.TextField(blank=True),
        ),
    ]
