# Generated by Django 5.0.3 on 2024-05-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image_url',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item_qna',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_qna',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='user_qna_images', verbose_name='image_url'),
        ),
    ]
