# Generated by Django 5.0.3 on 2024-05-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_board_image_url_alter_cart_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='image_url'),
        ),
    ]
