# Generated by Django 5.0.3 on 2024-05-31 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_kind', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(max_length=1000, upload_to='')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.board')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.board')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.image')),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_kind_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.pet_species')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.pet_breed')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.pet_gender')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.pet_species')),
            ],
        ),
    ]
