# Generated by Django 5.0.6 on 2024-06-03 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_pet_age_alter_pet_breed_alter_pet_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replied_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_amount', models.IntegerField()),
                ('patmentId', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.user')),
            ],
        ),
    ]
