# Generated by Django 5.0.3 on 2024-06-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_orderitem_is_refund_orderitem_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_refund',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.CharField(blank=True, choices=[('cat', 'Cat'), ('dog', 'Dog'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('board', 'Board'), ('item', 'Item')], max_length=10)),
                ('content_id', models.IntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('search', 'Search'), ('review', 'Review'), ('purchase', 'Purchase'), ('bookmark', 'Bookmark'), ('comment', 'Comment')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stay_time', models.DurationField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_content_type', models.CharField(choices=[('board', 'Board'), ('item', 'Item')], max_length=10)),
                ('recommended_content_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
