# Generated by Django 5.0.3 on 2024-06-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_interaction_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.payment'),
        ),
    ]
