# Generated by Django 5.0.3 on 2024-06-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_orderitem_is_refund_orderitem_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
