# Generated by Django 5.0.3 on 2024-06-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_interaction_content_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_tag',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RemoveField(
            model_name='image_tag',
            name='image_id',
        ),
    ]
