# Generated by Django 5.0.3 on 2024-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_review_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='isEdited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
