# Generated by Django 5.0.3 on 2024-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_reply_isedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_tag',
            name='tagId',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
