# Generated by Django 5.0.3 on 2024-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_image_tag_tagid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='user_qna_images', verbose_name='image_url'),
        ),
    ]
