export const BOARD_LIST_REQUEST = 'BOARD_LIST_REQUEST'
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS'
export const BOARD_LIST_FAIL = 'BOARD_LIST_FAIL'

export const BOARD_DETAILS_REQUEST = 'BOARD_DETAILS_REQUEST'
export const BOARD_DETAILS_SUCCESS = 'BOARD_DETAILS_SUCCESS'
export const BOARD_DETAILS_FAIL = 'BOARD_DETAILS_FAIL'