export const CART_ITEM_LIST_REQUEST = "CART_ITEM_LIST_REQUEST";
export const CART_ITEM_LIST_SUCCESS = "CART_ITEM_LIST_SUCCESS";
export const CART_ITEM_LIST_FAIL = "CART_ITEM_LIST_FAIL";



export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";

export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAIL = "CART_REMOVE_ITEM_FAIL";

export const CART_QTY_UPDATE_REQUEST = "CART_QTY_UPDATE_REQUEST";
export const CART_QTY_UPDATE_SUCCESS = "CART_QTY_UPDATE_SUCCESS";
export const CART_QTY_UPDATE_FAIL = "CART_QTY_UPDATE_FAIL";
