export const QNA_LIST_REQUEST = 'QNA_LIST_REQUEST'
export const QNA_LIST_SUCCESS = 'QNA_LIST_SUCCESS'
export const QNA_LIST_FAIL = 'QNA_LIST_FAIL'

export const QNA_DETAILS_REQUEST = 'QNA_DETAILS_REQUEST'
export const QNA_DETAILS_SUCCESS = 'QNA_DETAILS_SUCCESS'
export const QNA_DETAILS_FAIL = 'QNA_DETAILS_FAIL'

export const QNA_CREATE_REQUEST = 'QNA_CREATE_REQUEST'
export const QNA_CREATE_SUCCESS = 'QNA_CREATE_SUCCESS'
export const QNA_CREATE_FAIL = 'QNA_CREATE_FAIL'
export const QNA_CREATE_RESET = 'QNA_CREATE_RESET'

export const QNA_UPDATE_REQUEST = 'QNA_UPDATE_REQUEST'
export const QNA_UPDATE_SUCCESS = 'QNA_UPDATE_SUCCESS'
export const QNA_UPDATE_FAIL = 'QNA_UPDATE_FAIL'
export const QNA_UPDATE_RESET = 'QNA_UPDATE_RESET'

export const QNA_DELETE_REQUEST = 'QNA_DELETE_REQUEST'
export const QNA_DELETE_SUCCESS = 'QNA_DELETE_SUCCESS'
export const QNA_DELETE_FAIL = 'QNA_DELETE_FAIL'
