export const QNA_LIST_REQUEST = 'QNA_LIST_REQUEST'
export const QNA_LIST_SUCCESS = 'QNA_LIST_SUCCESS'
export const QNA_LIST_FAIL = 'QNA_LIST_FAIL'

export const QNA_DETAILS_REQUEST = 'QNA_DETAILS_REQUEST'
export const QNA_DETAILS_SUCCESS = 'QNA_DETAILS_SUCCESS'
export const QNA_DETAILS_FAIL = 'QNA_DETAILS_FAIL'

export const QNA_CREATE_REQUEST = 'QNA_CREATE_REQUEST'
export const QNA_CREATE_SUCCESS = 'QNA_CREATE_SUCCESS'
export const QNA_CREATE_FAIL = 'QNA_CREATE_FAIL'
export const QNA_CREATE_RESET = 'QNA_CREATE_RESET'